trigger:
  branches:
    include:
      - dev
      - staging
      - main

variables:
  - group: KssFrontend
  - group: KssGlobal

pool:
  vmImage: ubuntu-latest

stages:
- stage: ScanAndBuild
  displayName: 'Scan and Build app'
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
  - job: SecretScan
    displayName: 'Secret and Credential Scan'
    steps:
    - checkout: self
      fetchDepth: '0'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Install Python'
    - script: |
        pip install truffleHog3
        trufflehog3 --format json --output truffleHog-report.json .
        if [ -s truffleHog-report.json ] && [ "$(cat truffleHog-report.json)" != "[]" ]; then
          echo "##[error]Secrets detected in repository!"
          cat truffleHog-report.json
          exit 1
        fi
      displayName: 'Run TruffleHog Secret Scan'

  - job: ReactBuild
    displayName: 'React Vite Build'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '24.x'
      displayName: 'Install Node.js'
    - script: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm run build
      displayName: 'Build App'

- stage: BuildAndDeploy
  displayName: 'Build Image And Deploy'
  condition: or(
    eq(variables['Build.SourceBranchName'], 'staging'),
    eq(variables['Build.SourceBranchName'], 'main')
    )

  jobs:
  - job: BuildImage
    displayName: 'Build Docker Image'
    steps:
    - checkout: self
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | bash
        az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        az acr login --name $(ACR_NAME)

        IMAGE=$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)
        docker build -t $IMAGE .
        docker push $IMAGE

        if [ "$(Build.SourceBranchName)" = "main" ]; then
          ENV="production"
          RESOURCE_GROUP=$(RESOURCE_GROUP_PROD)
          ACA_NAME=$(ACA_NAME_PROD)
        elif [ "$(Build.SourceBranchName)" = "staging" ]; then
          ENV="staging"
          RESOURCE_GROUP=$(RESOURCE_GROUP_DEV)
          ACA_NAME=$(ACA_NAME_DEV)
        fi

        az containerapp update --resource-group $RESOURCE_GROUP --name $ACA_NAME --image $IMAGE
