/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AgentRouteRouteImport } from './routes/agent/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBranchesRouteImport } from './routes/admin/branches'
import { Route as AuthAgentVerifyRouteImport } from './routes/auth/agent/verify'
import { Route as AuthAgentLoginRouteImport } from './routes/auth/agent/login'
import { Route as AuthAdminVerifyRouteImport } from './routes/auth/admin/verify'
import { Route as AuthAdminSetupRouteImport } from './routes/auth/admin/setup'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'
import { Route as AuthAdminCheckRouteImport } from './routes/auth/admin/check'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users.create'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers_.$customerId'
import { Route as AdminCustomersCreateRouteImport } from './routes/admin/customers.create'
import { Route as AdminBranchesCreateRouteImport } from './routes/admin/branches.create'

const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthAgentVerifyRoute = AuthAgentVerifyRouteImport.update({
  id: '/agent/verify',
  path: '/agent/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAgentLoginRoute = AuthAgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminVerifyRoute = AuthAdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminSetupRoute = AuthAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminCheckRoute = AuthAdminCheckRouteImport.update({
  id: '/admin/check',
  path: '/admin/check',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCustomersCreateRoute = AdminCustomersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminBranchesCreateRoute = AdminBranchesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminBranchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/branches/create': typeof AdminBranchesCreateRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/auth/admin/check': typeof AuthAdminCheckRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/setup': typeof AuthAdminSetupRoute
  '/auth/admin/verify': typeof AuthAdminVerifyRoute
  '/auth/agent/login': typeof AuthAgentLoginRoute
  '/auth/agent/verify': typeof AuthAgentVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/initialize': typeof InitializeRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/branches/create': typeof AdminBranchesCreateRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/auth/admin/check': typeof AuthAdminCheckRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/setup': typeof AuthAdminSetupRoute
  '/auth/admin/verify': typeof AuthAdminVerifyRoute
  '/auth/agent/login': typeof AuthAgentLoginRoute
  '/auth/agent/verify': typeof AuthAgentVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/admin/branches': typeof AdminBranchesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/branches/create': typeof AdminBranchesCreateRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/customers_/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/auth/admin/check': typeof AuthAdminCheckRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/setup': typeof AuthAdminSetupRoute
  '/auth/admin/verify': typeof AuthAdminVerifyRoute
  '/auth/agent/login': typeof AuthAgentLoginRoute
  '/auth/agent/verify': typeof AuthAgentVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/initialize'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/users'
    | '/admin/'
    | '/agent/'
    | '/auth/'
    | '/admin/branches/create'
    | '/admin/customers/create'
    | '/admin/customers/$customerId'
    | '/admin/users/create'
    | '/auth/admin/check'
    | '/auth/admin/login'
    | '/auth/admin/setup'
    | '/auth/admin/verify'
    | '/auth/agent/login'
    | '/auth/agent/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/initialize'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/users'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/admin/branches/create'
    | '/admin/customers/create'
    | '/admin/customers/$customerId'
    | '/admin/users/create'
    | '/auth/admin/check'
    | '/auth/admin/login'
    | '/auth/admin/setup'
    | '/auth/admin/verify'
    | '/auth/agent/login'
    | '/auth/agent/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/initialize'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/users'
    | '/admin/'
    | '/agent/'
    | '/auth/'
    | '/admin/branches/create'
    | '/admin/customers/create'
    | '/admin/customers_/$customerId'
    | '/admin/users/create'
    | '/auth/admin/check'
    | '/auth/admin/login'
    | '/auth/admin/setup'
    | '/auth/admin/verify'
    | '/auth/agent/login'
    | '/auth/agent/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InitializeRoute: typeof InitializeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/agent/verify': {
      id: '/auth/agent/verify'
      path: '/agent/verify'
      fullPath: '/auth/agent/verify'
      preLoaderRoute: typeof AuthAgentVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/agent/login': {
      id: '/auth/agent/login'
      path: '/agent/login'
      fullPath: '/auth/agent/login'
      preLoaderRoute: typeof AuthAgentLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/admin/verify': {
      id: '/auth/admin/verify'
      path: '/admin/verify'
      fullPath: '/auth/admin/verify'
      preLoaderRoute: typeof AuthAdminVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/admin/setup': {
      id: '/auth/admin/setup'
      path: '/admin/setup'
      fullPath: '/auth/admin/setup'
      preLoaderRoute: typeof AuthAdminSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/admin/check': {
      id: '/auth/admin/check'
      path: '/admin/check'
      fullPath: '/auth/admin/check'
      preLoaderRoute: typeof AuthAdminCheckRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/customers_/$customerId': {
      id: '/admin/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/create': {
      id: '/admin/customers/create'
      path: '/create'
      fullPath: '/admin/customers/create'
      preLoaderRoute: typeof AdminCustomersCreateRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/branches/create': {
      id: '/admin/branches/create'
      path: '/create'
      fullPath: '/admin/branches/create'
      preLoaderRoute: typeof AdminBranchesCreateRouteImport
      parentRoute: typeof AdminBranchesRoute
    }
  }
}

interface AdminBranchesRouteChildren {
  AdminBranchesCreateRoute: typeof AdminBranchesCreateRoute
}

const AdminBranchesRouteChildren: AdminBranchesRouteChildren = {
  AdminBranchesCreateRoute: AdminBranchesCreateRoute,
}

const AdminBranchesRouteWithChildren = AdminBranchesRoute._addFileChildren(
  AdminBranchesRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersCreateRoute: typeof AdminCustomersCreateRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCreateRoute: AdminCustomersCreateRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersCreateRoute: AdminUsersCreateRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBranchesRoute: AdminBranchesRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgentRouteRouteChildren {
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminCheckRoute: typeof AuthAdminCheckRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminSetupRoute: typeof AuthAdminSetupRoute
  AuthAdminVerifyRoute: typeof AuthAdminVerifyRoute
  AuthAgentLoginRoute: typeof AuthAgentLoginRoute
  AuthAgentVerifyRoute: typeof AuthAgentVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminCheckRoute: AuthAdminCheckRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminSetupRoute: AuthAdminSetupRoute,
  AuthAdminVerifyRoute: AuthAdminVerifyRoute,
  AuthAgentLoginRoute: AuthAgentLoginRoute,
  AuthAgentVerifyRoute: AuthAgentVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InitializeRoute: InitializeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
