/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainURouteRouteImport } from './routes/_main.u/route'
import { Route as AuthAuthRouteRouteImport } from './routes/_auth.auth/route'
import { Route as MainUIndexRouteImport } from './routes/_main.u/index'
import { Route as AuthAuthIndexRouteImport } from './routes/_auth.auth/index'
import { Route as MainUUsersRouteImport } from './routes/_main.u/users'
import { Route as MainUCustomersRouteImport } from './routes/_main.u/customers'
import { Route as MainUUsersCreateRouteImport } from './routes/_main.u/users.create'
import { Route as MainUCustomersCreateRouteImport } from './routes/_main.u/customers.create'
import { Route as AuthAuthUOtpRouteImport } from './routes/_auth.auth/u.otp'
import { Route as AuthAuthULoginRouteImport } from './routes/_auth.auth/u.login'
import { Route as AuthAuthUInitializeRouteImport } from './routes/_auth.auth/u.initialize'

const MainURouteRoute = MainURouteRouteImport.update({
  id: '/_main/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRouteRoute = AuthAuthRouteRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUIndexRoute = MainUIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainURouteRoute,
} as any)
const AuthAuthIndexRoute = AuthAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const MainUUsersRoute = MainUUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainURouteRoute,
} as any)
const MainUCustomersRoute = MainUCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MainURouteRoute,
} as any)
const MainUUsersCreateRoute = MainUUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainUUsersRoute,
} as any)
const MainUCustomersCreateRoute = MainUCustomersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainUCustomersRoute,
} as any)
const AuthAuthUOtpRoute = AuthAuthUOtpRouteImport.update({
  id: '/u/otp',
  path: '/u/otp',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const AuthAuthULoginRoute = AuthAuthULoginRouteImport.update({
  id: '/u/login',
  path: '/u/login',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const AuthAuthUInitializeRoute = AuthAuthUInitializeRouteImport.update({
  id: '/u/initialize',
  path: '/u/initialize',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthAuthRouteRouteWithChildren
  '/u': typeof MainURouteRouteWithChildren
  '/u/customers': typeof MainUCustomersRouteWithChildren
  '/u/users': typeof MainUUsersRouteWithChildren
  '/auth/': typeof AuthAuthIndexRoute
  '/u/': typeof MainUIndexRoute
  '/auth/u/initialize': typeof AuthAuthUInitializeRoute
  '/auth/u/login': typeof AuthAuthULoginRoute
  '/auth/u/otp': typeof AuthAuthUOtpRoute
  '/u/customers/create': typeof MainUCustomersCreateRoute
  '/u/users/create': typeof MainUUsersCreateRoute
}
export interface FileRoutesByTo {
  '/u/customers': typeof MainUCustomersRouteWithChildren
  '/u/users': typeof MainUUsersRouteWithChildren
  '/auth': typeof AuthAuthIndexRoute
  '/u': typeof MainUIndexRoute
  '/auth/u/initialize': typeof AuthAuthUInitializeRoute
  '/auth/u/login': typeof AuthAuthULoginRoute
  '/auth/u/otp': typeof AuthAuthUOtpRoute
  '/u/customers/create': typeof MainUCustomersCreateRoute
  '/u/users/create': typeof MainUUsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/auth': typeof AuthAuthRouteRouteWithChildren
  '/_main/u': typeof MainURouteRouteWithChildren
  '/_main/u/customers': typeof MainUCustomersRouteWithChildren
  '/_main/u/users': typeof MainUUsersRouteWithChildren
  '/_auth/auth/': typeof AuthAuthIndexRoute
  '/_main/u/': typeof MainUIndexRoute
  '/_auth/auth/u/initialize': typeof AuthAuthUInitializeRoute
  '/_auth/auth/u/login': typeof AuthAuthULoginRoute
  '/_auth/auth/u/otp': typeof AuthAuthUOtpRoute
  '/_main/u/customers/create': typeof MainUCustomersCreateRoute
  '/_main/u/users/create': typeof MainUUsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/u'
    | '/u/customers'
    | '/u/users'
    | '/auth/'
    | '/u/'
    | '/auth/u/initialize'
    | '/auth/u/login'
    | '/auth/u/otp'
    | '/u/customers/create'
    | '/u/users/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/u/customers'
    | '/u/users'
    | '/auth'
    | '/u'
    | '/auth/u/initialize'
    | '/auth/u/login'
    | '/auth/u/otp'
    | '/u/customers/create'
    | '/u/users/create'
  id:
    | '__root__'
    | '/_auth/auth'
    | '/_main/u'
    | '/_main/u/customers'
    | '/_main/u/users'
    | '/_auth/auth/'
    | '/_main/u/'
    | '/_auth/auth/u/initialize'
    | '/_auth/auth/u/login'
    | '/_auth/auth/u/otp'
    | '/_main/u/customers/create'
    | '/_main/u/users/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthAuthRouteRoute: typeof AuthAuthRouteRouteWithChildren
  MainURouteRoute: typeof MainURouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main/u': {
      id: '/_main/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof MainURouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/u/': {
      id: '/_main/u/'
      path: '/'
      fullPath: '/u/'
      preLoaderRoute: typeof MainUIndexRouteImport
      parentRoute: typeof MainURouteRoute
    }
    '/_auth/auth/': {
      id: '/_auth/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthAuthIndexRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/_main/u/users': {
      id: '/_main/u/users'
      path: '/users'
      fullPath: '/u/users'
      preLoaderRoute: typeof MainUUsersRouteImport
      parentRoute: typeof MainURouteRoute
    }
    '/_main/u/customers': {
      id: '/_main/u/customers'
      path: '/customers'
      fullPath: '/u/customers'
      preLoaderRoute: typeof MainUCustomersRouteImport
      parentRoute: typeof MainURouteRoute
    }
    '/_main/u/users/create': {
      id: '/_main/u/users/create'
      path: '/create'
      fullPath: '/u/users/create'
      preLoaderRoute: typeof MainUUsersCreateRouteImport
      parentRoute: typeof MainUUsersRoute
    }
    '/_main/u/customers/create': {
      id: '/_main/u/customers/create'
      path: '/create'
      fullPath: '/u/customers/create'
      preLoaderRoute: typeof MainUCustomersCreateRouteImport
      parentRoute: typeof MainUCustomersRoute
    }
    '/_auth/auth/u/otp': {
      id: '/_auth/auth/u/otp'
      path: '/u/otp'
      fullPath: '/auth/u/otp'
      preLoaderRoute: typeof AuthAuthUOtpRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/_auth/auth/u/login': {
      id: '/_auth/auth/u/login'
      path: '/u/login'
      fullPath: '/auth/u/login'
      preLoaderRoute: typeof AuthAuthULoginRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/_auth/auth/u/initialize': {
      id: '/_auth/auth/u/initialize'
      path: '/u/initialize'
      fullPath: '/auth/u/initialize'
      preLoaderRoute: typeof AuthAuthUInitializeRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
  }
}

interface AuthAuthRouteRouteChildren {
  AuthAuthIndexRoute: typeof AuthAuthIndexRoute
  AuthAuthUInitializeRoute: typeof AuthAuthUInitializeRoute
  AuthAuthULoginRoute: typeof AuthAuthULoginRoute
  AuthAuthUOtpRoute: typeof AuthAuthUOtpRoute
}

const AuthAuthRouteRouteChildren: AuthAuthRouteRouteChildren = {
  AuthAuthIndexRoute: AuthAuthIndexRoute,
  AuthAuthUInitializeRoute: AuthAuthUInitializeRoute,
  AuthAuthULoginRoute: AuthAuthULoginRoute,
  AuthAuthUOtpRoute: AuthAuthUOtpRoute,
}

const AuthAuthRouteRouteWithChildren = AuthAuthRouteRoute._addFileChildren(
  AuthAuthRouteRouteChildren,
)

interface MainUCustomersRouteChildren {
  MainUCustomersCreateRoute: typeof MainUCustomersCreateRoute
}

const MainUCustomersRouteChildren: MainUCustomersRouteChildren = {
  MainUCustomersCreateRoute: MainUCustomersCreateRoute,
}

const MainUCustomersRouteWithChildren = MainUCustomersRoute._addFileChildren(
  MainUCustomersRouteChildren,
)

interface MainUUsersRouteChildren {
  MainUUsersCreateRoute: typeof MainUUsersCreateRoute
}

const MainUUsersRouteChildren: MainUUsersRouteChildren = {
  MainUUsersCreateRoute: MainUUsersCreateRoute,
}

const MainUUsersRouteWithChildren = MainUUsersRoute._addFileChildren(
  MainUUsersRouteChildren,
)

interface MainURouteRouteChildren {
  MainUCustomersRoute: typeof MainUCustomersRouteWithChildren
  MainUUsersRoute: typeof MainUUsersRouteWithChildren
  MainUIndexRoute: typeof MainUIndexRoute
}

const MainURouteRouteChildren: MainURouteRouteChildren = {
  MainUCustomersRoute: MainUCustomersRouteWithChildren,
  MainUUsersRoute: MainUUsersRouteWithChildren,
  MainUIndexRoute: MainUIndexRoute,
}

const MainURouteRouteWithChildren = MainURouteRoute._addFileChildren(
  MainURouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthAuthRouteRoute: AuthAuthRouteRouteWithChildren,
  MainURouteRoute: MainURouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
